MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "checkpoint/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
DATASETS:
  TRAIN: ("sparseviews_scannetv2_plane_train",)
  TEST: ("sparseviews_scannetv2_plane_test",)
SOLVER:
  IMS_PER_BATCH: 16 
  BASE_LR: 0.0001
  CHECKPOINT_PERIOD: 2156 # 1078*2  17237/16 ≈ 1078
  STEPS: (6468, 12936) # (6, 12)*1078,
  MAX_ITER: 17248 # 16*1078
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  IMAGE_SIZE: (192, 256)
  MIN_SCALE: 0.5
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "sparseviews_scannetv2_plane"
  RESIZE: True
  BRIGHT_COLOR_CONTRAST: False
TEST:
  EVAL_PERIOD: 17249 
  VIS_PERIOD: 50
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
VERSION: 2