_BASE_: Base-Segmentation.yaml

INPUT:
  IMAGE_SIZE: (480, 640) 
SOLVER:
  IMS_PER_BATCH: 8 
  # STEPS: (127744,143712) # !(32, 36)*3992,
  # MAX_ITER: 151696 # ! 38*3992
  STEPS: (127744,159680) # !(32, 40 )*3992,
  MAX_ITER: 167664 # ! 42*3992


MODEL:
  META_ARCHITECTURE: "PlaneRecTR"
  # CAMERA_ON: False
  SEM_SEG_HEAD:
    NAME: "MaskFormerHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 2 # 2,0 for non-plane/non-label, 1 for plane
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    DEPTH_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "MultiScaleMaskedTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True  # = aux_loss 
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 0.2
    MASK_WEIGHT: 0.5
    DICE_WEIGHT: 0.5
    PARAM_L1_WEIGHT: 0.1
    PARAM_COS_WEIGHT: 0.5
    Q_WEIGHT: 0.2
    CENTER_WEIGHT: 0.1
    PLANE_DEPTHS_WEIGHT: 0.2
    WHOLE_DEPTH_WEIGHT: 0.2

    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 30 
    NHEADS: 8 
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 19200 # (480/4)*(640/4) = 120*160=19200
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    PREDICT_CENTER: False
    PREDICT_PARAM: True
    PREDICT_DEPTH: True
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: True

      PLANE_SCORE_THRESHOLD: 0.6
      MASK_PROB_THRESHOLD: 0.5
      OVERLAP_THRESHOLD: 0.6

      PLANE_MASK_THRESHOLD: 0.001

      OUTPUTDIR_FOR_RESULTS: None
      SAVE_OUTPUT: False
    
  CAMERA_MODULE:
    PREDICT_POSES: True
    CAMERA_DECODER_NAME: ViTEss
    NOESS: False
    # NO_POS_ENCODING: True
    CROSS_FEATURES: True #!
    USE_SINGLE_SOFTMAX: False
    # L1_POS_ENCODING: False
    FC_HIDDEN_SIZE: 512 #? pose_regressor hidden size
    TRANSFORMER_DEPTH: 1
    FUSION_TRANSFORMER: True
    NUM_HEADS: 4 #! 
    POSE_TR_WEIGHT: 5.0
    POSE_ROT_WEIGHT: 15.0
    ###########The useless loss from the previous experiment, to be deleted
    PREDICT_INVERSE_POSES: False
    INVERSE_POSE_TR_WEIGHT: 2.5
    INVERSE_POSE_ROT_WEIGHT: 7.5
    PREDICT_JOINT_CORR_POSE_PARAM: False
    JOINT_CORR_POSE_PARAM_L1_WEIGHT: 3.0
    JOINT_CORR_POSE_PARAM_COS_WEIGHT: 3.0
    PREDICT_JOINT_GTCORR_POSE_GTPARAM: False
    JOINT_GTCORR_POSE_GTPARAM_L1_WEIGHT: 3.0
    JOINT_GTCORR_POSE_GTPARAM_COS_WEIGHT: 5.0
    PREDICT_JOINT_01CORR_POSE_PARAMDETACH: False
    JOINT_01CORR_POSE_PARAMDETACH_OFFSET_WEIGHT: 3.0
    JOINT_01CORR_POSE_PARAMDETACH_COS_WEIGHT: 5.0
    CORRS_WEIGHT: 0.2
    ##########################################################
    DECOUPLING: 0
    PHASE2_TFM: True #!
    PARAM_ENCODING: False
    CENTER_ENCODING: False
    PREDICT_CORRS: False
    FILTER_CAM_PLANES: False
    ATTN1_TRANSPOSE: False
    ATTN2_TRANSPOSE: True #!
    CONSISTENT_MLP_LAYERS: 0
    CROSS_PP_EMBEDDING: False
    MASK2CENTER: False
    ONE_HEAD_KQ: True #!
    TEST:
      MATCH_THRESHOLD: 0.2
      FILTER_CORR_PLANES: True
  # DEVICE: "cpu"

    
